version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb-local
    #cap_add:
    # - SYS_NICE
    #restart: always
    #environment:
    #- MONGO_INITDB_ROOT_USERNAME=user
    #- MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
    volumes:
      - mongo-db:/data/db
    networks:
      - mongo-network 

volumes:
  mongo-db:
    driver: local

networks:
  mongo-network:
    driver: bridge
