version: '3.8'
services:
  cache:
    image: redis:latest
    container_name: redis-local
    #restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass minhbien123
    volumes:
      - redis-cache:/data
volumes:
  redis-cache:
    driver: local
